Camp/config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get 'static_pages/home'
  post '/micro', to:'microposts#create'
  get '/micro',to:'microposts#new'

  devise_for :users

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    get '/users/sign_in' => 'devise/sessions#new'
  end
  
  resources :users
  resources :microposts


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Camp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Camp/app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :title, presence: true, length: { maximum: 20 }
  validates :content, presence: true, length: { maximum: 140 }
end

Camp/app/models/user.rb
class User < ApplicationRecord
  has_many :microposts, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
end

Camp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

Camp/app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
    before_action :authenticate_user!,only:[:create,:destroy]
    before_action :correct_user,   only: :destroy

 

    def show
      @micropost = Micropost.find(params[:id])
      @user = User.find_by(id: @micropost.user_id)

        @microposts=Micropost.all.order(created_at: 'desc')
        REDIS.zincrby "microposts/", 1, "#{@micropost.id}"
        REDIS.incr "microposts/#{@micropost.id}"
       
    end
    

    def new
      @micropost = Micropost.new
    end

    def create
      @micropost = current_user.microposts.build(micropost_params)

        if @micropost.save
          flash[:success] = "Micropost created!"
          redirect_to root_url
        else
          render 'new'
        end
    end
  
    def destroy
      @micropost.destroy
      flash[:success] = "Micropost deleted"
      redirect_to request.referrer || root_url
    end

    def edit
      @micropost = Micropost.find(params[:id])
    end

    def update
        @micropost = Micropost.find(params[:id])
        if @micropost.update(micropost_params)
            redirect_to root_path
        else
            render 'edit'
        end

    end
  
    private
  
      def micropost_params
        params.require(:micropost).permit(:title,:content)
      end
      
      def correct_user
        @micropost = current_user.microposts.find_by(id: params[:id])
        redirect_to root_url if @micropost.nil?
      end
end

Camp/app/controllers/redis_controller.rb
class RedisController < ApplicationController

end

Camp/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if user_signed_in?
      @microposts = current_user.microposts.build
    end
    @microposts=Micropost.all.order(created_at: 'desc')
   

  end

  def show
    @user = User.find(params[:id])
    @micropost = Micropost.find(params[:id])
  end
end

Camp/app/helpers/application_helper.rb
module ApplicationHelper
end

Camp/app/helpers/microposts_helper.rb
module MicropostsHelper
end

Camp/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

Camp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                               'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application',
                               'data-turbolinks-track': 'reload' %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>
    <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
 <header>
    <p id="logo"><a href="http://192.168.33.10:3000">RailsCamp<span>Blog</span></a></p>
    <nav>
        <ul>
            <li><a href="http://192.168.33.10:3000">トップ</a></li>
            <% if user_signed_in? %>
              <li><a href="http://192.168.33.10:3000/micro">新規投稿</a></li>
              <li>
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
              </li>
            <% else %>
              <li><a href="http://192.168.33.10:3000/users/sign_up">新規登録</a></li>
              <li><a href="http://192.168.33.10:3000/users/sign_in">ログイン</a></li>

              
            <% end %>
        </ul>
    </nav>
    <div class="clear"></div>
</header>
        <nav>
          <ul class="nav navbar-nav navbar-right">

          </ul>
        </nav>
      </div>
    </header>
    <div class="container">
      <%= yield %>
    </div>

    <footer>
    <div id="footer_inner">
        <p>Copyright RailsCamp 2015 All Rights Reserved</p>
    </div>
</footer>
  </body>
</html>

Camp/app/views/microposts/_index.html.erb
<ul>
<% if @microposts.present?%>
<% @microposts.each do |a|%>
    
    <div>
    
    <h2><%= link_to a.title,micropost_path(a)%></h2>
    <% if user_signed_in? && current_user.id == a.user_id%>
    <%= link_to "削除", a, method: :delete,
                                       data: { confirm: "You sure?" } %>
    <%= link_to "編集",  edit_micropost_path(a) %>                          
    <% end %>
    <%time=a.created_at%>
    <p><%=   time.strftime('%y/%m/%d')%></p>

    </div>
<% end %>
<% end %>
</ul>

Camp/app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
  <span class="title"><%= micropost.title %></span>
</li>

Camp/app/views/microposts/edit.html.erb
<% provide(:title, 'micro') %>
<div class="title">
<h1>編集</h1>
</div>
<%= form_for @micropost, url: micropost_path(@micropost) do |f|%>
<%= render 'shared/error_messages', object: f.object %>

  <div class="titlearea">
  <%= f.text_field :title, placeholder: "enter title" %>
  </div>
  
  <div class="textarea">
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
  </div>
  <div class="botan">
  <%= f.submit "Post", class: "btn btn-primary" %>
  </div>
<% end %>

Camp/app/views/microposts/new.html.erb
<% provide(:title, 'micro') %>
<div class="title">
<h1>新規投稿</h1>
</div>

<%= form_for(@micropost) do |f| %>
<%= render 'shared/error_messages', object: f.object %>

  <div class="titlearea">
  <%= f.text_field :title, placeholder: "enter title" %>
  </div>
  
  <div class="textarea">
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
  </div>
  <div class="botan">
  <%= f.submit "Post", class: "btn btn-primary" %>
  </div>
<% end %>

Camp/app/views/microposts/show.html.erb
<!DOCTYPE html>
<html>
<head lang="ja">
    <meta charset="UTF-8">
    <link rel="stylesheet" href="style.css" type="text/css" media="screen">
</head>
<body>



<div id="title">
    <div>
       
    <%time=@micropost.created_at%>
    <p><%=   time.strftime('%y/%m/%d')%>
    <%=   @user.email%>

        </p>
        <h1><%=@micropost.title %></h1>
    </div>
</div>

<div id="article_wrap">

    <%= @micropost.content%>

    <div id="sidebar">
        
        <h2>★PV数ランキング</h2>
        <ul>
           <%= render'static_pages/index'%>
        </ul>
    </div>
    <div class="clear"></div>
</div>



</body>
</html>

Camp/app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

Camp/app/views/static_pages/home.html.erb
<!DOCTYPE html>
<html>
<head lang="ja">
    <meta charset="UTF-8">
    <title>Rails Camp Blog</title>
    <link rel="stylesheet" href="style.scss" type="text/css" media="screen">
</head>

<body>
<div id="main">
<%= link_to image_tag("main-img.jpg", alt: "Rails logo"),
            'http://rubyonrails.org/' %>
</div>



<div id="article_wrap">

    <div id="article_list">
      <h3>Microposts </h3>

       <%= render 'microposts/index' %>
       

    </div>
    </div>


      <div id="sidebar">
        
        <h2>★PV数ランキング</h2>

        <ul>
            <%= render 'static_pages/index' %>
        </ul>
    </div>
    <div class="clear"></div>
</div>



</body>
</html>